language:
  - ruby
before_install:
  - sudo apt-get update -qq
  - gem update bundler
bundler_args: --verbose
sudo: required
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
before_script:
  - bundle list
  - sudo apt-get install -y wkhtmltopdf
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env: WKHTMLTOPDF_BIN=/usr/bin/wkhtmltopdf
script:
  - bundle exec rake
matrix:
  include:
    - rvm: 1.8.7
      before_install:
        - sudo apt-get update -qq
        - gem update --system 1.8.25
        - gem --version
      gemfile: gemfiles/2.3.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: 1.9.2
      gemfile: gemfiles/3.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/3.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/3.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/4.0.gemfile
    - rvm: ruby-head
