name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: CI Rails ${{ matrix.rails }} on ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails: ["7.1.3", "7.0.8", "6.1.7"]
        ruby: ["3.3.4", "3.2.4", "3.1.6", "3.0.6", "2.7.8"]
        include:
          #- rails: "5.0"
          #  ruby: 2.7.8
          - rails: "5.1"
            ruby: 2.7.8
          - rails: "5.2"
            ruby: 2.7.8
          - rails: "6.0.6"
            ruby: 2.7.8
          - rails: "7.0"
            ruby: truffleruby

    env:
      WKHTMLTOPDF_BIN: /usr/bin/wkhtmltopdf
      RUBY_VERSION: ${{ matrix.ruby }}
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v3

      - name: Install OS dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y wkhtmltopdf

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests with Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
        run: bundle exec rake
